# Generated by Django 3.2.9 on 2022-01-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='languages',
        ),
        migrations.AddField(
            model_name='projects',
            name='languages',
            field=models.ManyToManyField(to='my_portfolio.Languages'),
        ),
    ]
